### ISSUE TITLE
Checkpoints missed file

### ISSUE THREAD

**Issue by Vlr17** [pvougiou/Neural-Wikipedian#2]
The checkpoint.zip miss the file 'surf_form_tuples.model.t7.summaries_Testing.beam_5.h5' for the D1 dataset of the LSTM network amd both for the GRU net

**Comment by pvougiou** [comment]
You can create these HDF5 files by running the `beam-sample.lua` file for each system (i.e. Triples2GRU and Triples2LSTM) you're interested in. 

Assuming that all necessary libraries are installed, you only need the checkpoint files of each pre-trained model (e.g. `surf_form_tuples.model.t7` and `uris.model.t7`) and the pre-processed dataset files, both of which should be downloaded in their corresponding directories after running the respective `download_trained_models.sh` and `download_datasets.sh` scripts.
